<?php

use app\controllers\AboutUsController;
use app\controllers\Controller;
use app\views\ViewSettings;

/* @var AboutUsController $this */

$settings = new ViewSettings(
    title: "Over ons | Wiskunde Woordenboek",
    stylesheets: ["templates/header", "templates/footer", "about-us-view"],
    scripts: ["heading-anchors"],
);
?>
<!DOCTYPE html>
<html lang="nl">
<?php
require Controller::getTemplatePath("head");
?>
<body>
<?php
require Controller::getTemplatePath("header");
?>
<main id="main" class="text">
    <h1 id="over-ons">Over ons</h1>
    <p>
        Deze website is geschreven door mij, Frederik van der Els. Ik heb een Bachelor of Science in de wiskunde en ben
        momenteel premaster student Technische Informatica aan de TU Delft. Naast mijn studie ben ik parttime SOC
        analyst bij Fox-IT. Deze website heb ik dan ook voor mijn plezier gemaakt. Als je geïnteresseerd bent in hoe,
        kijk dan <a href="https://github.com/xpple/wiskundewoordenboek.nl/" target="_blank">hier</a>.
    </p>
</main>
<?php
require Controller::getTemplatePath("footer");
?>
</body>
</html>
