<?php

use app\controllers\Controller;
use app\controllers\ExistingWordController;
use app\util\Constants;
use app\views\ViewSettings;

global $f;

/* @var ExistingWordController $this */

$settings = new ViewSettings(
    title: htmlspecialchars($this->wordModel->wordCapitalised) . " | Wiskunde Woordenboek",
    stylesheets: ["templates/header", "templates/footer", "templates/word-list", "existing-word-view"],
    scripts: ["heading-anchors", "required-inputs", "existing-word-view/preview-changes", "existing-word-view/submit-changes"],
    mathsEnabled: true,
    markdownEnabled: true,
);
?>
<!DOCTYPE html>
<html lang="nl">
<?php
require Controller::getTemplatePath("head");
?>
<body>
<?php
require Controller::getTemplatePath("header");
?>
<div id="container">
    <main id="main">
        <div id="title-container">
            <h1 id="<?= htmlspecialchars($this->wordModel->wordDirectory) ?>"><?= htmlspecialchars($this->wordModel->wordCapitalised) ?></h1>
<?php
            $formal = ($_GET["betekenis"] ?? null) === "formeel";
            ?>
            <form id="meaning-option-form" method="get">
                <label for="option-standard">Standaard</label>
                <input id="option-standard" name="betekenis" value="standaard" type="radio" onchange="this.form.submit()" <?= !$formal ? "checked" : "" ?>>
                <label for="option-formal">Formeel</label>
                <input id="option-formal" name="betekenis" value="formeel" type="radio" onchange="this.form.submit()" <?= $formal ? "checked" : "" ?>>
            </form>
        </div>
<?php if (!$formal): ?>
        <div id="meaning-div" class="text render-tex render-markdown"><?= htmlspecialchars($this->wordModel->meaning) ?></div>
<?php else: ?>
        <div id="meaning-div" class="text render-tex render-markdown"><?= htmlspecialchars($this->wordModel->formalMeaning) ?></div>
<?php endif ?>
    </main>
    <aside id="recently-added-container">
        <h2 id="recent-toegevoegd">Recent toegevoegd</h2>
        <ol class="word-list">
<?php
        foreach($this->recentlyAddedWords as $wordModel) {
            echo <<<HTML
            <li><a href="/woord/{$f(htmlspecialchars(urlencode($wordModel->wordDirectory)))}/">{$f(htmlspecialchars($wordModel->wordCapitalised))}</a></li>\n
HTML;
            }
        ?>
        </ol>
    </aside>
    <section id="make-changes-container" class="text">
        <h2 id="aanpassingen-aanbrengen">Aanpassingen aanbrengen</h2>
        <p class="render-tex">
            Als er foutieve informatie op de pagina staat, of als je informatie wilt toevoegen, kun je hier aanpassingen
            voorstellen. Omschrijf je aanpassingen zo duidelijk mogelijk. Je kunt gebruik maken van de opmaaktaal
            <a href="https://nl.wikipedia.org/wiki/LaTeX">LaTeX</a> om wiskundige formules te schrijven. Zo wordt
            <code class="inline">$x^2$</code> bijvoorbeeld omgezet naar $x^2$. Je kunt ook gebruik maken van (een deel
            van) <a href="https://nl.wikipedia.org/wiki/Markdown">Markdown</a>. Afbeeldingen kun je invoegen met
            <code class="inline">![tekst voor als de afbeelding niet beschikbaar is](https://domein.nl/afbeelding.png)</code>.
            Rond je aanpassingen af met een korte beschrijving waarin je je wijzigingen samenvat. Optioneel kun je je
            e-mailadres bijvoegen om de aanpassingen verder te bespreken. Een kopie van je wijzigingen wordt ook naar je
            gestuurd.
        </p>
        <form id="make-changes-form" method="post">
            <div id="changes-label-container">
                <label for="changes-textarea">Aanpassingen</label>
                <div id="display-option-div">
                    <button id="write-button" type="button">Schrijven</button>
                    <button id="preview-button" type="button">Voorbeeld</button>
                </div>
            </div>
            <textarea id="changes-textarea" name="changes" rows="10" maxlength="<?= Constants::DISCORD_EMBED_MAX_FIELD_VALUE ?>" required></textarea>
            <div id="changes-div" style="display: none"></div>
            <label for="description-input">Beschrijving</label>
            <input id="description-input" name="description" type="text" maxlength="<?= Constants::DISCORD_EMBED_MAX_FIELD_VALUE ?>" required>
            <label for="email-input">E-mailadres</label>
            <input id="email-input" name="email" type="email" maxlength="<?= Constants::DISCORD_EMBED_MAX_FIELD_VALUE ?>">
            <button id="submit-button" type="submit">Indienen</button>
            <input name="meaning" value="<?= !$formal ? "standaard" : "formeel" ?>" type="hidden">
        </form>
        <output id="make-changes-output" form="make-changes-form"></output>
    </section>
</div>
<?php
require Controller::getTemplatePath("footer");
?>
</body>
</html>
