<?php

use app\controllers\Controller;
use app\controllers\NewWordController;
use app\util\Constants;
use app\views\ViewSettings;

global $f;

/* @var NewWordController $this */

$settings = new ViewSettings(
    title: htmlspecialchars($this->word) . " creëren | Wiskunde Woordenboek",
    stylesheets: ["templates/header", "templates/footer", "templates/word-list", "new-word-view"],
    scripts: ["heading-anchors", "required-inputs", "new-word-view/preview-changes", "new-word-view/submit-changes", "new-word-view/heading-updater"],
    mathsEnabled: true,
    markdownEnabled: true,
);
?>
<!DOCTYPE html>
<html lang="nl">
<?php
require Controller::getTemplatePath("head");
?>
<body>
<?php
require Controller::getTemplatePath("header");
?>
<div id="container">
    <main id="main">
        <form id="create-page-form" method="post">
            <div id="title-container">
                <h1 id="<?= htmlspecialchars($this->word) ?>"><input id="title-input" name="name" value="<?= htmlspecialchars($this->word) ?>" type="text" maxlength="<?= Constants::DB_MAX_NAME_LENGTH ?>" required></h1>
                <div id="meaning-option-div">
                    <label for="option-standard">Standaard</label>
                    <input id="option-standard" name="meaning" value="standaard" type="radio" checked>
                    <label for="option-formal">Formeel</label>
                    <input id="option-formal" name="meaning" value="formeel" type="radio">
                </div>
            </div>
            <div id="content-label-container">
                <label for="content-textarea">Inhoud</label>
                <div id="display-option-div">
                    <button id="write-button" type="button">Schrijven</button>
                    <button id="preview-button" type="button">Voorbeeld</button>
                </div>
            </div>
            <textarea id="content-textarea" name="content" rows="20" maxlength="<?= Constants::DISCORD_EMBED_MAX_FIELD_VALUE ?>" required></textarea>
            <div id="content-div" class="text" style="display: none"></div>
            <label for="description-input">Beschrijving</label>
            <input id="description-input" name="description" type="text" maxlength="<?= Constants::DISCORD_EMBED_MAX_FIELD_VALUE ?>" required>
            <label for="email-input">E-mailadres</label>
            <input id="email-input" name="email" type="email" maxlength="<?= Constants::DISCORD_EMBED_MAX_FIELD_VALUE ?>">
            <button id="submit-button" type="submit">Indienen</button>
            <input name="type" value="creatie" type="hidden">
        </form>
        <output id="create-page-output" form="create-page-form"></output>
    </main>
    <aside id="recently-added-container">
        <h2 id="recent-toegevoegd">Recent toegevoegd</h2>
        <ol class="word-list">
<?php
        foreach($this->recentlyAddedWords as $wordModel) {
            echo <<<HTML
            <li><a href="/woord/{$f(htmlspecialchars(urlencode($wordModel->wordDirectory)))}/">{$f(htmlspecialchars($wordModel->wordCapitalised))}</a></li>\n
HTML;
            }
        ?>
        </ol>
    </aside>
</div>
<?php
require Controller::getTemplatePath("footer");
?>
</body>
</html>
