<footer id="footer">
    <div id="footer-links">
        <ul>
            <li><a href="/contact/">Contact</a></li>
            <li><a href="/over-ons/">Over ons</a></li>
            <li><a href="https://github.com/xpple/wiskundewoordenboek.nl/" target="_blank">Broncode</a></li>
        </ul>
    </div>
    <div id="footer-social-media">
        <ul>
            <li><a href="https://www.linkedin.com/in/frederikvdels/" target="_blank"><img src="/assets/img/linkedin.svg" alt="LinkedIn icon">LinkedIn</a></li>
            <li><a href="https://github.com/xpple/" target="_blank"><img src="/assets/img/github.svg" alt="GitHub icon">GitHub</a></li>
        </ul>
    </div>
    <div id="footer-copyright">
        <p>
            <small>Copyright&copy; Wiskunde Woordenboek 2024</small>
        </p>
    </div>
</footer>
