<header id="header">
    <div id="banner">
        <a href="/"><img src="/assets/img/logo.png" alt="Logo"></a>
        <form id="search" action="/zoek" method="post">
            <input id="search-input" name="query" type="text">
            <label id="search-label" for="search-input"><img src="/assets/img/search.svg" alt="Search icon"></label>
        </form>
    </div>
    <nav id="nav">
        <ol>
<?php
            foreach(range('a','z') as $letter) {
                echo <<<HTML
            <li><a href="/letter/$letter/">$letter</a></li>\n
HTML;
            }
            ?>
        </ol>
    </nav>
</header>
