<?php

use App\Controllers\AboutUsController;
use App\Controllers\Controller;
use App\Views\ViewSettings;

/* @var AboutUsController $this */

$settings = new ViewSettings(
    title: "Over ons | Wiskunde Woordenboek",
    stylesheets: ["templates/header", "templates/footer", "about-us-view"],
    scripts: ["heading-anchors"],
);
?>
<!DOCTYPE html>
<html lang="nl">
<?php
require Controller::getTemplatePath("head");
?>
<body>
<?php
require Controller::getTemplatePath("header");
?>
<main id="main">
    <h1 id="over-ons">Over ons</h1>
    <p>
        Deze website is geschreven door mij, Frederik van der Els, derdejaars student Technische Wiskunde aan de TU
        Delft. Naast mijn studie ben ik parttime SOC analyst bij Fox-IT. Ik vind ik informatica namelijk ook erg leuk.
        Deze website heb ik dan ook voor mijn plezier gemaakt. Als je geïnteresseerd bent in hoe, kijk dan <a href="https://github.com/xpple/wiskundewoordenboek.nl/" target="_blank">hier</a>.
    </p>
</main>
<?php
require Controller::getTemplatePath("footer");
?>
</body>
</html>
