<?php

use App\Controllers\Controller;
use App\Controllers\ErrorController;
use App\Util\HttpException;

/* @var ErrorController $this */
?>
<!DOCTYPE html>
<html lang="nl">
<?php
$title = $this->cause->getMessage() . " | Wiskunde Woordenboek";
require Controller::getTemplatePath("head");
?>
<body>
<?php
require Controller::getTemplatePath("header");
?>
<main>
    <h2><?= $this->cause instanceof HttpException ? $this->cause->getCode() . ": " . $this->cause->getMessage() : "Er heeft zich een onbekende fout opgetreden." ?></h2>
</main>
<?php
require Controller::getTemplatePath("footer");
?>
</body>
</html>
