<?php

use App\Controllers\Controller;
use App\Controllers\ErrorController;
use App\Util\HttpException;
use App\Views\ViewSettings;

/* @var ErrorController $this */

$settings = new ViewSettings(
    title: $this->cause->getMessage() . " | Wiskunde Woordenboek",
    stylesheets: ["templates/header", "templates/footer", "error-view"],
    scripts: ["heading-anchors"],
);
?>
<!DOCTYPE html>
<html lang="nl">
<?php
require Controller::getTemplatePath("head");
?>
<body>
<?php
require Controller::getTemplatePath("header");
?>
<main id="main" class="text">
    <h1><?= $this->cause instanceof HttpException ? $this->cause->getCode() . ": " . $this->cause->getMessage() : "Er heeft zich een onbekende fout opgedaan." ?></h1>
</main>
<?php
require Controller::getTemplatePath("footer");
?>
</body>
</html>
