<?php

use App\Controllers\Controller;
use App\Controllers\IndexController;
use App\Views\ViewSettings;

/* @var IndexController $this */

$settings = new ViewSettings(
    title: "Wiskunde Woordenboek",
    stylesheets: array("templates/header", "index-view"),
);
?>
<!DOCTYPE html>
<html lang="nl">
<?php
require Controller::getTemplatePath("head");
?>
<body>
<?php
require Controller::getTemplatePath("header");
?>
<main>

</main>
<?php
require Controller::getTemplatePath("footer");
?>
</body>
</html>
