<?php

use App\Controllers\Controller;
use App\Controllers\LetterController;
use App\Views\ViewSettings;

/* @var LetterController $this */

$settings = new ViewSettings(
    title: "$this->letter | Wiskunde Woordenboek",
    stylesheets: array("templates/header", "templates/word-list", "letter-view"),
);
?>
<!DOCTYPE html>
<html lang="nl">
<?php
require Controller::getTemplatePath("head");
?>
<body>
<?php
require Controller::getTemplatePath("header");
?>
<main>
    <h2><?= htmlspecialchars($this->letter) ?></h2>
    <ol class="word-list">
<?php
        foreach($this->wordModels as $wordModel) {
            echo <<<HTML
        <li><a href="/woord/$wordModel->wordDirectory/">$wordModel->wordCapitalised</a></li>\n
HTML;
        }
        ?>
    </ol>
</main>
<?php
require Controller::getTemplatePath("footer");
?>
</body>
</html>
