<?php

use App\Controllers\Controller;
use App\Controllers\SearchController;
use App\Views\ViewSettings;

global $f;

/* @var SearchController $this */

$settings = new ViewSettings(
    title: "Zoeken | Wiskunde Woordenboek",
    stylesheets: ["templates/header", "templates/footer", "templates/word-list", "search-view"],
    scripts: ["heading-anchors"]
);
?>
<!DOCTYPE html>
<html lang="nl">
<?php
require Controller::getTemplatePath("head");
?>
<body>
<?php
require Controller::getTemplatePath("header");
?>
<main id="main">
    <h1 id="zoekresultaten"><?= "Zoekresultaten voor \"" . htmlspecialchars($this->query) . "\":" ?></h1>
<?php if (empty($this->wordModels)): ?>
    <p>
        Geen woord kwam overeen met jouw zoekopdracht, probeer iets anders.
    </p>
<?php else: ?>
    <ol class="word-list">
<?php
        foreach($this->wordModels as $wordModel) {
            echo <<<HTML
        <li><a href="/woord/{$f(htmlspecialchars(urlencode($wordModel->wordDirectory)))}/">{$f(htmlspecialchars($wordModel->wordCapitalised))}</a></li>\n
HTML;
        }
        ?>
    </ol>
<?php endif ?>
</main>
<?php
require Controller::getTemplatePath("footer");
?>
</body>
</html>
