<?php

use App\Controllers\Controller;
use App\Controllers\SearchController;
use App\Views\ViewSettings;

global $f;

/* @var SearchController $this */

$settings = new ViewSettings(
    title: "Zoeken | Wiskunde Woordenboek",
    stylesheets: ["templates/header", "templates/word-list", "search-view"],
);
?>
<!DOCTYPE html>
<html lang="nl">
<?php
require Controller::getTemplatePath("head");
?>
<body>
<?php
require Controller::getTemplatePath("header");
?>
<main>
    <h2 id="zoekresultaten"><?= "Zoekresultaten voor \"" . htmlspecialchars($this->query) . "\":" ?></h2>
    <ol class="word-list">
<?php
        foreach($this->wordModels as $wordModel) {
            echo <<<HTML
        <li><a href="/woord/{$f(htmlspecialchars(urlencode($wordModel->wordDirectory)))}/">{$f(htmlspecialchars($wordModel->wordCapitalised))}</a></li>\n
HTML;
        }
        ?>
    </ol>
</main>
<?php
require Controller::getTemplatePath("footer");
?>
</body>
</html>
