<?php

use App\Controllers\Controller;
use App\Controllers\SearchController;

/* @var SearchController $this */
?>
<!DOCTYPE html>
<html lang="nl">
<?php
$title = "Zoeken | Wiskunde Woordenboek";
require Controller::getTemplatePath("head");
?>
<body>
<?php
require Controller::getTemplatePath("header");
?>
<main>
    <h2><?= "Zoekresultaten voor \"" . htmlspecialchars($this->query) . "\":" ?></h2>
    <ul>
<?php
        foreach($this->wordModels as $wordModel) {
            echo <<<HTML
        <li><a href="/woord/$wordModel->wordDirectory">$wordModel->wordCapitalised</a></li>\n
HTML;
        }
        ?>
    </ul>
</main>
<?php
require Controller::getTemplatePath("footer");
?>
</body>
</html>
