<?php

use App\Controllers\Controller;
use App\Controllers\WordController;
use App\Views\ViewSettings;

/* @var WordController $this */

$settings = new ViewSettings(
    title: $this->wordModel->wordCapitalised . " | Wiskunde Woordenboek",
    stylesheets: array("templates/header", "templates/word-list", "word-view"),
    mathsEnabled: true,
);
?>
<!DOCTYPE html>
<html lang="nl">
<?php
require Controller::getTemplatePath("head");
?>
<body>
<?php
require Controller::getTemplatePath("header");
?>
<div id="container">
    <main id="main">
        <div id="title-container">
            <h2><?= htmlspecialchars($this->wordModel->wordCapitalised) ?></h2>
<?php
            $formal = ($_GET["betekenis"] ?? null) === "formeel";
            ?>
            <form id="meaning-option" method="get">
                <label for="option-standard">Standaard</label>
                <input id="option-standard" name="betekenis" value="standaard" type="radio" onchange="this.form.submit()" <?= !$formal ? "checked" : "" ?>>
                <label for="option-formal">Formeel</label>
                <input id="option-formal" name="betekenis" value="formeel" type="radio" onchange="this.form.submit()" <?= $formal ? "checked" : "" ?>>
            </form>
        </div>
<?php if (!$formal): ?>
        <p id="meaning">
            <?= htmlspecialchars($this->wordModel->meaning) ?>
        </p>
<?php else: ?>
        <p id="meaning">
            <?= htmlspecialchars($this->wordModel->formalMeaning) ?>
        </p>
<?php endif ?>
    </main>
    <aside id="recently-added">
        <h2>Recent toegevoegd</h2>
        <ol class="word-list">
<?php
            foreach($this->recentlyAddedWords as $wordModel) {
                echo <<<HTML
        <li><a href="/woord/$wordModel->wordDirectory/">$wordModel->wordCapitalised</a></li>\n
HTML;
            }
            ?>
        </ol>
    </aside>
</div>
<?php
require Controller::getTemplatePath("footer");
?>
</body>
</html>
